DinhVu_ThueOto/MVC_Thue_Oto/Controllers/IndexThueXeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Thue_Oto.Models;

namespace MVC_Thue_Oto.Controllers
{
    public class IndexThueXeController : Controller
    {
        DB_Thue_OtoDataContext data = new DB_Thue_OtoDataContext();
        //tao doi tuong lay danh sach xe moi
        private List<XeDichVu> Layds(int count) {
            return data.XeDichVus.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }
        public ActionResult Index()
        {
            var xemoi = Layds(9);
            return View(xemoi);
        }
        //tao doi tuong loai cho ngoi de sap xep theo loai
        public ActionResult LoaiChoNgoi() {
            var loaichongoi = from lcn in data.LoaiChoNgois select lcn;
            return PartialView(loaichongoi);
        }
        //tao ra doi tuong dong xe ma khach hang yeu cau
        public ActionResult LoaiHangXe() {
            var loaihangxe = from hx in data.HangXes select hx;
            return PartialView(loaihangxe);
        }
        //tao theo loai cho ngoi
        public ActionResult TheoLoaiChoNgoi(int id) {
            var x = from cn in data.XeDichVus where cn.MaChoNgoi == id select cn;
            return View(x);
        }

        //tao theo loai cac chiet xe
        public ActionResult TheoDongXe(int id) {
            var xx = from dx in data.XeDichVus where dx.MaHang == id select dx;
            return View(xx);
        }

        //tao ra trang chi tiet cac san pham
        public ActionResult ChiTietXe(int id) {
            var xxx = from ctx in data.XeDichVus where ctx.MaDVXe == id select ctx;
            return View(xxx);
        }
    }
}

DinhVu_ThueOto/MVC_Thue_Oto/Views/IndexThueXe/ChiTietXe.cshtml
@model IEnumerable<MVC_Thue_Oto.Models.XeDichVu>
<style type="text/css">
    #Datmua a {
        clear: both;
        background-color: red;
        color: white;
        width: 120px;
        height: 35px;
        display: block;
        float: right;
        text-align: center;
        padding-top: 10px;
        text-decoration: none;
        font-weight: bold;
    }

        #Datmua a:hover {
            background-color: gray;
            color: red;
        }
</style>
@{
    ViewBag.Title = "ChiTietXe";
    Layout = "~/Views/Shared/_PlayOutUser.cshtml";
}

<h2>Thông Tin Chi Tiết Xe</h2>
@foreach (var item in Model)
{
    <div>
        <div style="width:40%; float:left; border-left: dotted 1px; border-color:azure">
            <img src="~/Content/Images/Images_Car/@item.TenHinh" width="100%" />
        </div>
        <div style="width:60%; float:left; padding:10px">
            <h4 style="font-weight:bold; color:red">Tên sách: @item.TenXe </h4>
            <p style="text-align:justify"><Span style="font-weight:bold"></Span>@item.ThongTinHopSo</p>
            <p style="text-align:justify"><Span style="font-weight:bold"></Span>@item.NhienLieuTP</p>
            <p style="text-align:justify"><Span style="font-weight:bold"></Span>@item.NhienLieuNTP</p>
        </div>
        <div>
            <div id="Datmua">
                <a href="@Url.Action("AddToCard", "ShoppingCard", new { id = @item.MaDVXe })" class="list-group-item">
                    Đặt xe
                </a>
            </div>
        </div>
    </div>
}

DinhVu_ThueOto/MVC_Thue_Oto/Views/IndexThueXe/Index.cshtml
@model IEnumerable<MVC_Thue_Oto.Models.XeDichVu>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_PlayOutUser.cshtml";
}

<div class="top_1">
    <div class="color_top1">
        Các xe được thuê nhiếu
    </div>
</div>
@foreach (var item in Model) {

        <div class="car">
            <a href="@Url.Action("ChiTietXe","IndexThueXe",new{id = item.MaDVXe})" class="list-group-item list assad_1">
                <div class="img">
                    <img alt="@item.TenHinh" src="~/Content/Images/Images_Car/@item.TenHinh" height="250" width="270" />
                </div>
                <div class="content_car1">@item.TenXe</div>
       </a>
</div>
}

DinhVu_ThueOto/MVC_Thue_Oto/Views/IndexThueXe/LoaiChoNgoi.cshtml
@model IEnumerable<MVC_Thue_Oto.Models.LoaiChoNgoi>

<div class="backroud_right_1">
    <div class="color_top1_r">Loại chổ ngồi</div>
</div>
@foreach (var item in Model) {
   <div>
       <a href="@Url.Action("TheoLoaiChoNgoi","IndexThueXe",new{id = item.MaChoNgoi})" class="list-group-item list assad_1">
           <div style="padding-left:20px; border:1px solid ; padding-bottom:5px; padding-top:5px">
               @item.SoChoNgoi
           </div>
       </a>
   </div>
   <div class="clear"></div>
}

DinhVu_ThueOto/MVC_Thue_Oto/Views/IndexThueXe/LoaiHangXe.cshtml
@model IEnumerable<MVC_Thue_Oto.Models.HangXe>

<div class="backroud_right_1">
    <div class="color_top1_r">Dòng Xe</div>
</div>
@foreach (var item in Model)
{
    <div>
        <a href="@Url.Action("TheoDongXe","IndexThueXe",new{id = item.MaHang})" class="list-group-item list assad_1">
            <div style="padding-left:20px; border:1px solid ; padding-bottom:5px; padding-top:5px">
                @item.TenHang
            </div>
        </a>
    </div>
    <div class="clear"></div>
}

DinhVu_ThueOto/MVC_Thue_Oto/Views/IndexThueXe/TheoDongXe.cshtml
@model IEnumerable<MVC_Thue_Oto.Models.XeDichVu>
@{
    ViewBag.Title = "TheoDongXe";
    Layout = "~/Views/Shared/_PlayOutUser.cshtml";
}

<div class="top_1">
    <div class="color_top2">
        Danh sách theo hãng xe
    </div>
</div>
@foreach (var item in Model)
{
    <a href="@Url.Action("ChiTietXe","IndexThueXe",new{id = item.MaDVXe})" class="list-group-item list assad_1">
        <div class="car">
            <div class="img">
                <img alt="@item.TenHinh" src="~/Content/Images/Images_Car/@item.TenHinh" height="250" width="270" />
            </div>
            <div class="content_car1">@item.TenXe</div>
        </div>
     </a>
}

DinhVu_ThueOto/MVC_Thue_Oto/Views/IndexThueXe/TheoLoaiChoNgoi.cshtml
@model IEnumerable<MVC_Thue_Oto.Models.XeDichVu>
@{
    ViewBag.Title = "TheoLoaiChoNgoi";
    Layout = "~/Views/Shared/_PlayOutUser.cshtml";
}

<div class="top_1">
    <div class="color_top2">
        Danh sách theo chổ ngồi
    </div>
</div>
@foreach (var item in Model)
{
    <a href="@Url.Action("ChiTietXe","IndexThueXe",new{id = item.MaDVXe})" class="list-group-item list assad_1">
        <div class="car">
            <div class="img">
                <img alt="@item.TenHinh" src="~/Content/Images/Images_Car/@item.TenHinh" height="250" width="270" />
            </div>
            <div class="content_car1">@item.TenXe</div>
        </div>
    </a>
}